FROM dustynv/nano_llm:humble-r36.3.0

ENV ROS_DISTRO=humble ROS_ROOT=/opt/ros PIP_INDEX_URL=https://pypi.org/simple

RUN apt update || true && apt install curl -y && \
    curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg && \
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F42ED6FBAB17C654

RUN apt update && \
    DEBIAN_FRONTEND="noninteractive" apt install -y \
        ros-$ROS_DISTRO-rmw-fastrtps-cpp \
        ros-$ROS_DISTRO-rmw-cyclonedds-cpp \
        ros-$ROS_DISTRO-rosbridge-server \
        ros-$ROS_DISTRO-ament-cmake

RUN python3 -m pip install "opencv-python>=4.8.1.78" && \
    python3 -m pip install "typing-extensions>=4.4.0" && \
    python3 -m pip install "ultralytics==8.3.168" && \
    python3 -m pip install "lap>=0.5.12" && \
    python3 -m pip install "numpy<2"
    
RUN mkdir -p /ros2_ws/src
COPY ros_entrypoint.sh /ros_entrypoint.sh
RUN chmod +x /ros_entrypoint.sh
ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]